SELECT tablespace_name, file_name, bytes FROM dba_temp_files WHERE tablespace_name = 'TEMP';
ALTER DATABASE TEMPFILE 'C:\Oracle19\oradata\DELL\TEMP01.DBF ' DROP INCLUDING DATAFILES;
ALTER TABLESPACE temp ADD TEMPFILE 'C:\Oracle19\oradata\DELL\TEMP01.DBF ' SIZE 512m AUTOEXTEND ON NEXT 250m MAXSIZE UNLIMITED;
